###
GET http://localhost:3000/api/productos 

###
GET http://localhost:3000/api/productos/60b29d1951227637fc62d7c6

###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
        "title":"QuietComfort 35",
        "brand": "Bose",
        "category": "Headphones",
        "price": "299",
        "img": "bose-qc35",
        "sale": false,
        "service": false,
        "recommended": false,
        "popular": true

}

###
DELETE http://localhost:3000/api/productos/60b151682b91652e44613754

###
PUT http://localhost:3000/api/productos/60b29ed351227637fc62d7cc
Content-Type: application/json

{
    "title": "Otamatone Original"
}

###
GET http://localhost:3000/api/productos/cat/Keyboards

###
GET http://localhost:3000/api/productos/rec/true

###
GET http://localhost:3000/api/productos/pop/true

###
GET http://localhost:3000/api/productos/sales/true